variables:
  DOCKER_DRIVER: overlay2
  # Minu konteineri registri aadress AWS-s (Amazon Elastic Container Registry)
  # Asenda MINU_REGISTRI_NIMI
  DOCKER_REGISTRY: 662032419283.dkr.ecr.eu-north-1.amazonaws.com/facet
  DOCKER_PUBLIC_REGISTRY: 662032419283.dkr.ecr.eu-north-1.amazonaws.com/public
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  DOMAIN: facet.itb2203.tautar.ee

stages:
  - build
  - api_test
  - deploy

default:
  image:
    name: docker:28.5.1-alpine3.22
  services:
    - docker:28.5.1-alpine3.22
  before_script:
    - apk add --no-cache curl jq python3 py3-pip
    - pip install --break-system-packages awscli
    - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${DOCKER_REGISTRY}
  after_script:
    - docker logout ${DOCKER_REGISTRY}
  tags:
    - itb2203

build:back-end:
  only:
    - master
    - main
  script:
    - docker build -t ${DOCKER_REGISTRY}/back:${CI_COMMIT_SHA} --build-arg REGISTRY=${DOCKER_PUBLIC_REGISTRY} ./Backend/FacetApi/
    - docker push ${DOCKER_REGISTRY}/back:${CI_COMMIT_SHA}
  stage: build

build:front-end:
  only:
    - master
    - main
  script:
    - docker build -t ${DOCKER_REGISTRY}/front:${CI_COMMIT_SHA} --build-arg REGISTRY=${DOCKER_PUBLIC_REGISTRY} ./Frontend/
    - docker push ${DOCKER_REGISTRY}/front:${CI_COMMIT_SHA}
  stage: build

api_test:
  image:
    name: docker:28.5.1-alpine3.22
    entrypoint: ["/bin/sh", "-c"]
  only:
    - master
    - main
  script:
    - cd ApiTests
    - docker compose up --abort-on-container-exit --exit-code-from newman
    - docker compose down -v
  stage: api_test

deploy:
  when: manual
  only:
    - master
    - main
  before_script:
    # teeme kindlaks, et ssh on installitud
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )"

    # käivitame ssh
    - eval $(ssh-agent -s)

    # loome ssh kausta ja anname ssh kaustas lugemise, kirjutamise ja käivitamise õigused
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    # leiame kõik serveri public key-d ja usaldame neid runneri keskkonnas
    - ssh-keyscan ${DOMAIN} >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    # leiame kõik serveri public key-d ja usaldame neid runneri keskkonnas
    - ssh-keyscan ${DOMAIN} >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    # loeme GitLabi muutujatest private key
    - echo "("$SSH_PRIVATE_KEY" | tr -d '\r')"
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | tr -d '\r')

    # loome ssh ühenduse
    - ssh ubuntu@${DOMAIN} "(aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin ${DOCKER_REGISTRY}) && CI_COMMIT_SHA=${CI_COMMIT_SHA} docker compose -f ~/app/compose.yml up -d"
  after_script:
    - exit
  stage: deploy


  