services:
  postgres:
    image: ${DOCKER_PUBLIC_REGISTRY}/postgres:18-alpine
    container_name: api_db
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGPORT=5433
    ports:
      - "5433:5433"
    networks:
      - pg_net
  back_end:
    image: ${DOCKER_REGISTRY}/back:${CI_COMMIT_SHA}
    container_name: back_end
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=qwertyuiopasdfghjklzxcvbnm123456
      - Jwt__Issuer=Online JWT Builder
      - ConnectionStrings__Default=Host=db;Port=5433;Database=facet-db;Username=postgres;Password=postgres
    depends_on:
      - postgres
    networks:
      - pg_net
      - api_net
    links:
      - "postgres:db"
    volumes:
      - ./startup:/etc/startup
    entrypoint:
      [
        "/etc/startup/wait-for",
        "-t",
        "30",
        "db:5433",
        "--",
        "dotnet",
        "/app/FacetApi.dll",
      ]
  newman:
    image: ${DOCKER_PUBLIC_REGISTRY}/newman:alpine
    entrypoint:
      ["/etc/startup/wait-for", "-t", "30", "back_end:5000", "--", "newman"]
    container_name: newman
    depends_on:
      - postgres
      - back_end
    network_mode: "service:back_end"
    volumes:
      - ./startup:/etc/startup
      - ./newman/:/etc/newman/
      - ./test-files/:/etc/newman/test-files/
    command: run /etc/newman/facet.postman_collection.json -e facet.postman_environment.json
networks:
  pg_net:
  api_net: