services:
  postgres:
    image: postgres:18-alpine
    container_name: api_db
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGPORT=5433
    ports:
      - "5433:5433"
    networks:
      - pg_net
  back_end:
    image: ${DOCKER_REGISTRY}/back:${CI_COMMIT_SHA}
    #build: ../Backend/FacetApi
    container_name: back_end
    environment:
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - postgres
    networks:
      - pg_net
      - api_net
    links:
      - "postgres:db"
    volumes:
      - ./startup:/etc/startup
    entrypoint:
      [
        "/etc/startup/wait-for",
        "-t",
        "30",
        "db:5433",
        "--",
        "dotnet",
        "/app/FacetApi.dll",
      ]
  newman:
    image: postman/newman:alpine
    entrypoint:
      ["/etc/startup/wait-for", "-t", "30", "back_end:5000", "--", "newman"]
    container_name: newman
    depends_on:
      - postgres
      - back_end
    network_mode: "service:back_end"
    volumes:
      - ./startup:/etc/startup
      - ./newman/:/etc/newman/
    command: run /etc/newman/facet.postman_collection.json -e facet.postman_environment.json
networks:
  pg_net:
  api_net:
